load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library", "scala_binary")

scala_library(
    name = "infra",
    srcs = [
        "Infra.scala",
        ],
    visibility = ["//visibility:public"],
    deps = [ ]
)